In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("ESPORTISTAS_MOD7.csv", delimiter=";")
df.head(25)

               Atleta            Esporte  Ganhos_Totais
0        Lionel Messi            Futebol            639
1        Lebron James           Basquete            595
2   Cristiano Ronaldo            Futebol            565
3           Neymar Jr            Futebol            467
4       Stephen Curry           Basquete            452
5         Kevin Duart           Basquete            452
6       Roger Federer              Tenis            442
7      Canelo Alvarez               Boxe            442
8           Tom Brady  Futebol Americano            408
9    Giannis Antetoku           Basquete            397
10   Russel Westbrook           Basquete            388
11       James Harden           Basquete            365
12   Matthew Stafford  Futebol Americano            354
13     Aaron Rodgers   Futebol Americano            334
14        Tiger Woods              Golfe            334
15         Josh Allen  Futebol Americano            329
16     Lewis Hamilton      Automobilismo            319
17         Tyson Fury               Boxe            305
18        Naomi Osaka              Tenis            290
19     Damian Lillard           Basquete            282
20     Deshaun Watson  Futebol Americano            273
21      Klay Thompson           Basquete            273
22         Mike Trout           Beisebol            241
23    Patrick Mahomes  Futebol Americano            241
24        Primos Kirk  Futebol Americano            238

In [ ]:
df.groupby('Esporte')['Atleta'].count().reset_index().sort_values(by='Atleta', ascending=False)
# Groupby agrupa os dados do df pela coluna 'Esporte
# O count() conta o número de ocorrências da coluna 'Atleta'
# O reset_index() reseta o índice do resultado anterior
# O sort_values ordena os resultados do DataFrame pelo número de atletas

             Esporte  Atleta
1           Basquete       8
5  Futebol Americano       7
4            Futebol       3
3               Boxe       2
7              Tenis       2
0      Automobilismo       1
2           Beisebol       1
6              Golfe       1

Trazendo os valores em porcentagem

In [ ]:
contagem_por_esporte = df['Esporte'].value_counts(normalize=True).reset_index()
# O parâmetro normalize=True faz com que os resultados sejam normalizados, ou seja, as contagens são divididas pelo número total de entradas, para fornecer a proporção de cada esporte em relação ao total.
contagem_por_esporte

             Esporte  proportion
0           Basquete        0.32
1  Futebol Americano        0.28
2            Futebol        0.12
3              Tenis        0.08
4               Boxe        0.08
5              Golfe        0.04
6      Automobilismo        0.04
7           Beisebol        0.04

MÉDIA 1

In [ ]:
soma_ganhos = df['Ganhos_Totais'].sum() #soma da coluna 'Ganhos_Totais'
qtde_resgistros = len(df['Ganhos_Totais']) #quantidade de atletas, ou seja, quantidade de registros na coluna 'Ganhos_Totais'
media_ganhos = soma_ganhos / qtde_resgistros #cálculo da média

print("A média de ganhos totais dos atletas é:",media_ganhos)

A média de ganhos totais dos atletas é: 377.0

MÉDIA 2 (FUNÇÃO)

In [18]:
df['Ganhos_Totais'].mean() #média dos ganhos totais dos atletas usando o método mean() do pandas

np.float64(377.0)

MÉDIA DOS GANHOS TOTAIS POR ESPORTE

In [ ]:
df.groupby('Esporte')['Ganhos_Totais'].mean().reset_index().sort_values(by='Ganhos_Totais', ascending=False)

             Esporte  Ganhos_Totais
4            Futebol          557.0
1           Basquete          400.5
3               Boxe          373.5
7              Tenis          366.0
6              Golfe          334.0
0      Automobilismo          319.0
5  Futebol Americano          311.0
2           Beisebol          241.0

MEDIANA TOTAL

In [21]:
df['Ganhos_Totais'].median()

np.float64(354.0)

MEDIANA POR ESPORTE

In [22]:
df.groupby('Esporte')['Ganhos_Totais'].median().reset_index().sort_values(by='Ganhos_Totais', ascending=False)

             Esporte  Ganhos_Totais
4            Futebol          565.0
1           Basquete          392.5
3               Boxe          373.5
7              Tenis          366.0
6              Golfe          334.0
5  Futebol Americano          329.0
0      Automobilismo          319.0
2           Beisebol          241.0

MODA

In [23]:
df['Ganhos_Totais'].mode()

0    241
1    273
2    334
3    442
4    452
Name: Ganhos_Totais, dtype: int64

DESVIO PADRÃO

In [ ]:
desvio_padrao_por_esporte = df.groupby('Esporte')['Ganhos_Totais'].std().reset_index()

desvio_padrao_por_esporte

# Não tem como calcular desvio padrão de valor que aparece só uma vez

             Esporte  Ganhos_Totais
0      Automobilismo            NaN
1           Basquete     103.414561
2           Beisebol            NaN
3               Boxe      96.873629
4            Futebol      86.278618
5  Futebol Americano      62.960305
6              Golfe            NaN
7              Tenis     107.480231

DESCRIBE

In [ ]:
df.describe()

# A função describe() do pandas é usada para gerar estatísticas descritivas resumidas de um DataFrame. Ela fornece informações como contagem, média, desvio padrão, valores mínimos e máximos, e os quartis (25%, 50% e 75%) para cada coluna numérica do DataFrame. Essa função é útil para obter uma visão geral rápida dos dados e entender a distribuição das variáveis numéricas.

       Ganhos_Totais
count      25.000000
mean      377.000000
std       110.029541
min       238.000000
25%       290.000000
50%       354.000000
75%       442.000000
max       639.000000